version: '3'

services:
  nginx:
    build:
      context: config/nginx
      args:
        PROJECT_DOMAIN: ${PROJECT_DOMAIN}
        DOCUMENT_ROOT: ${DOCUMENT_ROOT}
        DEBIAN_VERSION: ${DEBIAN_VERSION}
        NGINX_VERSION: ${NGINX_VERSION}
    ports:
      - ${PORT_NGINX}:80
      - ${PORT_NGINX_SSL}:443
    networks:
      default:
        aliases:
          - ${PROJECT_DOMAIN}
    volumes:
      - ${PROJECT_PATH}:/var/www/project:cached
      - ${NGINX_LOG_PATH}:/var/log/nginx
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${USER_CONFIG_PATH}/certs-data/:/data/letsencrypt/
      - /etc/letsencrypt/:/etc/letsencrypt/
    depends_on:
      - php
    environment:
      - TZ=${DEFAULT_TIMEZONE}

  php:
    build:
      context: config/php
      args:
        USER_ID: ${USER_ID}
        GROUP_ID: ${GROUP_ID}
        PHP_VERSION: ${PHP_VERSION}
        DEFAULT_TIMEZONE: ${DEFAULT_TIMEZONE}
        PHP_MEMORY_LIMIT: ${PHP_MEMORY_LIMIT}
        NODE_JS_VERSION: ${NODE_JS_VERSION}
        XDEBUG_REMOTE_PORT: ${XDEBUG_REMOTE_PORT}
        XDEBUG_REMOTE_AUTOSTART: ${XDEBUG_REMOTE_AUTOSTART}
        XDEBUG_REMOTE_ENABLE: ${XDEBUG_REMOTE_ENABLE}
        XDEBUG_REMOTE_HOST: ${XDEBUG_REMOTE_HOST}
        XDEBUG_REMOTE_CONNECT_BACK: ${XDEBUG_REMOTE_CONNECT_BACK}
    volumes:
      - ${PROJECT_PATH}:/var/www/project:cached
      - ${SYMFONY_LOG_PATH}:/var/www/project/var/logs:cached
      - ${COMPOSER_PATH}/cache:/var/www/.composer/cache:cached
      - ${SSH_KEY_PATH}/id_rsa:/var/www/.ssh/id_rsa
      - ${SSH_KEY_PATH}/id_rsa.pub:/var/www/.ssh/id_rsa.pub
      - ${SSH_KEY_PATH}/known_hosts:/var/www/.ssh/known_hosts
      - ${USER_CONFIG_PATH}/.bash_history:/var/www/.bash_history
      - ./config/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/www.conf:ro
    depends_on:
      - mysql

  mysql:
    image: mysql:${MYSQL_VERSION}
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      TZ: ${DEFAULT_TIMEZONE}
    ports:
      - ${PORT_MYSQL}:3306
    volumes:
      - ${MYSQL_DATA_PATH}:/var/lib/mysql:cached
      - ${MYSQL_DUMP_PATH}:/tmp/db
    command: ['--character-set-server=${MYSQL_CHARACTER_SET_SERVER}', '--collation-server=${MYSQL_COLLATION_SERVER}']

  phpmyadmin:
    build:
      context: config/phpmyadmin
      args:
        PMA_CLIENT_MAX_BODY_SIZE: ${PMA_CLIENT_MAX_BODY_SIZE}
        PMA_MEMORY_LIMIT: ${PMA_MEMORY_LIMIT}
        PMA_POST_MAX_SIZE: ${PMA_POST_MAX_SIZE}
        PMA_UPLOAD_MAX_FILESIZE: ${PMA_UPLOAD_MAX_FILESIZE}
        DEFAULT_TIMEZONE: ${DEFAULT_TIMEZONE}

    environment:
      - PMA_HOST=mysql
      - TZ=${DEFAULT_TIMEZONE}
    ports:
      - ${PORT_PHPMYADMIN}:80
    volumes:
      - ./config/phpmyadmin/config.user.inc.php:/etc/phpmyadmin/config.user.inc.php

  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"

  redis:
    image: redis:latest
    environment:
      TZ: ${DEFAULT_TIMEZONE}
